<?php
namespace Jab\App\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Jab\Config\EntityBundle\Annotation as JAB;

/**
 * Person
 * Autogenerated: 2014-09-18 08:39:15
 *
 *  @JAB\Entity(
 *     managedEntity=true,
 *     type="CUSTOM"
 * )
 * @ORM\Table(name="person")
 * @ORM\Entity(repositoryClass="Jab\App\UserBundle\Entity\PersonRepository")
 */
class Person extends \Jab\Config\EntityBundle\Entity\JabEntity
{
    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=64, nullable=true, unique=false)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=64, nullable=true, unique=false)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="occupation", type="string", length=32, nullable=true, unique=false)
     */
    private $occupation;

    /**
     * @var string
     *
     * @ORM\Column(name="displayname", type="string", length=64, nullable=true, unique=false)
     */
    private $displayName;


    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setFirstName($firstName) {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName() {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Person
     */
    public function setLastName($lastName) {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName() {
        return $this->lastName;
    }

    /**
     * Set occupation
     *
     * @param string $occupation
     * @return Person
     */
    public function setOccupation($occupation) {
        $this->occupation = $occupation;
        return $this;
    }

    /**
     * Get occupation
     *
     * @return string
     */
    public function getOccupation() {
        return $this->occupation;
    }

    /**
     * Set displayName
     *
     * @param string $displayName
     * @return Person
     */
    public function setDisplayName($displayName) {
        $this->displayName = $displayName;
        return $this;
    }

    /**
     * Get displayName
     *
     * @return string
     */
    public function getDisplayName() {
        return ($this->displayName ? $this->displayName : $this->getFullName());
    }

    /** --- CUSTOM METHODS BEGIN --- */

    /**
     * @return string
     */
    public function getFullName() {
        return $this->firstName . ' ' . $this->lastName;
    }

    /** --- CUSTOM METHODS END --- */
}
