<?php

namespace Jab\Tool\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BubucsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BubucsRepository extends EntityRepository
{
}
