<?php
namespace Jab\Tool\TestBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Jab\Config\EntityBundle\Annotation as JAB;

/**
 * SuperPippo
 * Autogenerated: 2014-09-16 18:39:17
 *
 *  @JAB\Entity(
 *     managedEntity=true,
 *     type="CUSTOM"
 * )
 * @ORM\Table(name="super_pippo")
 * @ORM\Entity(repositoryClass="Jab\Tool\TestBundle\Entity\SuperPippoRepository")
 */
class SuperPippo extends \Jab\Config\EntityBundle\Entity\JabEntity
{
    /**
     * @var boolean
     *
     * @ORM\Column(name="namefile", type="boolean", nullable=true, unique=false)
     */
    private $namefile;

    /**
     * @var string
     *
     * @ORM\Column(name="asdasd", type="string", length=32, nullable=true, unique=false)
     */
    private $asdasd;


    /**
     * Set namefile
     *
     * @param boolean $namefile
     * @return SuperPippo
     */
    public function setNamefile($namefile) {
        $this->namefile = $namefile;
        return $this;
    }

    /**
     * Get namefile
     *
     * @return boolean
     */
    public function getNamefile() {
        return $this->namefile;
    }

    /**
     * Set asdasd
     *
     * @param string $asdasd
     * @return SuperPippo
     */
    public function setAsdasd($asdasd) {
        $this->asdasd = $asdasd;
        return $this;
    }

    /**
     * Get asdasd
     *
     * @return string
     */
    public function getAsdasd() {
        return $this->asdasd;
    }
}
