parameters:
    ###

services:
    jab.tool.template.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: jab.tool.template.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: mainMenu }

    jab.tool.template.menu.user:
        class: Knp\Menu\MenuItem
        factory_service: jab.tool.template.menu_builder
        factory_method: createUserMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: userMenu }

